spring:
  application:
    name: "configserver"
  profiles:
    active: "git"
  cloud:
    config:
      server:

        git:
          uri: "https://github.com/v1ct0rbr/easybank-config.git"
          default-label: "main"
          timeout: 10
          clone-on-start: true
          force-pull: true

#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "ZwyQ9pOvIc0L0MGxPyKA5sxQtmShjL53O2wCe82c2CtqWpSMCYfIacQKpaJzhA62"
logging:
  level:
    org.springframework.web: error
server:
  port: 8071