server:
  port: 9000
spring:
  application:
    name: "cards"
  datasource:
    #    url: jdbc:h2:mem:accountsdb
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  devtools:
    restart:
      enabled: true
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071"

#rabbitmq:
#  host: localhost
#  port: 5672
#  username: guest
#  password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"