services:

  rabbit:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: victorqueirogabr/configserver:s6
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP  || exit 1"
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 20s
    extends:
      file: common-config.yml
      service: microservice-base-config
  accounts:
    image: victorqueirogabr/accounts:s6
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-config-server
  loans:
    image: victorqueirogabr/loans:s6
    container_name: loans-ms
    ports:
      - "8089:8089"

    environment:
      SPRING_APPLICATION_NAME: "loans"

    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-config-server
  cards:
    image: victorqueirogabr/cards:s6
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-config-server

networks:
  easybank:
    driver: bridge